[2024-04-17 03:23:28,125] {processor.py:163} INFO - Started process (PID=175) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:23:28,127] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:23:28,129] {logging_mixin.py:109} INFO - [2024-04-17 03:23:28,129] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:23:28,138] {logging_mixin.py:109} INFO - [2024-04-17 03:23:28,136] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:23:28,174] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:23:28,190] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.081 seconds
[2024-04-17 03:23:58,329] {processor.py:163} INFO - Started process (PID=209) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:23:58,331] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:23:58,333] {logging_mixin.py:109} INFO - [2024-04-17 03:23:58,332] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:23:58,338] {logging_mixin.py:109} INFO - [2024-04-17 03:23:58,337] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:23:58,363] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:23:58,375] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.050 seconds
[2024-04-17 03:24:28,495] {processor.py:163} INFO - Started process (PID=243) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:24:28,497] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:24:28,498] {logging_mixin.py:109} INFO - [2024-04-17 03:24:28,498] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:24:28,502] {logging_mixin.py:109} INFO - [2024-04-17 03:24:28,501] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:24:28,528] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:24:28,541] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.051 seconds
[2024-04-17 03:24:58,654] {processor.py:163} INFO - Started process (PID=287) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:24:58,655] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:24:58,656] {logging_mixin.py:109} INFO - [2024-04-17 03:24:58,656] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:24:58,661] {logging_mixin.py:109} INFO - [2024-04-17 03:24:58,659] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:24:58,680] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:24:58,689] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.040 seconds
[2024-04-17 03:25:28,806] {processor.py:163} INFO - Started process (PID=321) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:25:28,808] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:25:28,809] {logging_mixin.py:109} INFO - [2024-04-17 03:25:28,809] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:25:28,814] {logging_mixin.py:109} INFO - [2024-04-17 03:25:28,813] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:25:28,837] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:25:28,850] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.050 seconds
[2024-04-17 03:25:58,966] {processor.py:163} INFO - Started process (PID=355) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:25:58,968] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:25:58,969] {logging_mixin.py:109} INFO - [2024-04-17 03:25:58,969] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:25:58,974] {logging_mixin.py:109} INFO - [2024-04-17 03:25:58,973] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:25:58,995] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:25:59,006] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.044 seconds
[2024-04-17 03:26:29,199] {processor.py:163} INFO - Started process (PID=408) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:26:29,201] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:26:29,202] {logging_mixin.py:109} INFO - [2024-04-17 03:26:29,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:26:29,206] {logging_mixin.py:109} INFO - [2024-04-17 03:26:29,205] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:26:29,226] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:26:29,236] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.042 seconds
[2024-04-17 03:26:59,335] {processor.py:163} INFO - Started process (PID=442) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:26:59,337] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:26:59,338] {logging_mixin.py:109} INFO - [2024-04-17 03:26:59,338] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:26:59,342] {logging_mixin.py:109} INFO - [2024-04-17 03:26:59,341] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:26:59,363] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:26:59,376] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.046 seconds
[2024-04-17 03:27:29,477] {processor.py:163} INFO - Started process (PID=476) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:29,479] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:27:29,480] {logging_mixin.py:109} INFO - [2024-04-17 03:27:29,479] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:29,485] {logging_mixin.py:109} INFO - [2024-04-17 03:27:29,484] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 218
    create_table_task >> prepare_dataset_task >> local_to_gcs_task >> gcs_to_bq_task
                                                                                   ^
IndentationError: unindent does not match any outer indentation level
[2024-04-17 03:27:29,511] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:29,523] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 0.052 seconds
[2024-04-17 03:27:35,500] {processor.py:163} INFO - Started process (PID=491) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:35,504] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:27:35,505] {logging_mixin.py:109} INFO - [2024-04-17 03:27:35,505] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:36,508] {logging_mixin.py:109} INFO - [2024-04-17 03:27:36,507] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 199, in <module>
    create_table_task = BigQueryCreateEmptyTableOperator(
NameError: name 'BigQueryCreateEmptyTableOperator' is not defined
[2024-04-17 03:27:36,524] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:36,533] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.038 seconds
[2024-04-17 03:27:50,626] {processor.py:163} INFO - Started process (PID=510) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:50,627] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:27:50,628] {logging_mixin.py:109} INFO - [2024-04-17 03:27:50,628] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:51,606] {logging_mixin.py:109} INFO - [2024-04-17 03:27:51,604] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 199, in <module>
    create_table_task = BigQueryCreateEmptyTableOperator(
NameError: name 'BigQueryCreateEmptyTableOperator' is not defined
[2024-04-17 03:27:51,621] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:27:51,630] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.008 seconds
[2024-04-17 03:28:21,763] {processor.py:163} INFO - Started process (PID=548) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:28:21,766] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:28:21,768] {logging_mixin.py:109} INFO - [2024-04-17 03:28:21,767] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:28:22,790] {logging_mixin.py:109} INFO - [2024-04-17 03:28:22,788] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 199, in <module>
    create_table_task = BigQueryCreateEmptyTableOperator(
NameError: name 'BigQueryCreateEmptyTableOperator' is not defined
[2024-04-17 03:28:22,805] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:28:22,814] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.056 seconds
[2024-04-17 03:28:52,953] {processor.py:163} INFO - Started process (PID=596) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:28:52,954] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:28:52,955] {logging_mixin.py:109} INFO - [2024-04-17 03:28:52,955] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:28:54,053] {logging_mixin.py:109} INFO - [2024-04-17 03:28:54,050] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_data_ingestion_gcs_dag.py", line 199, in <module>
    create_table_task = BigQueryCreateEmptyTableOperator(
NameError: name 'BigQueryCreateEmptyTableOperator' is not defined
[2024-04-17 03:28:54,071] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:28:54,081] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.134 seconds
[2024-04-17 03:29:05,164] {processor.py:163} INFO - Started process (PID=625) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:05,166] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:29:05,167] {logging_mixin.py:109} INFO - [2024-04-17 03:29:05,166] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:06,235] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:06,528] {logging_mixin.py:109} INFO - [2024-04-17 03:29:06,527] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:29:06,548] {logging_mixin.py:109} INFO - [2024-04-17 03:29:06,548] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:29:06,568] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.409 seconds
[2024-04-17 03:29:07,246] {processor.py:163} INFO - Started process (PID=634) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:07,248] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:29:07,249] {logging_mixin.py:109} INFO - [2024-04-17 03:29:07,249] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:08,345] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:08,351] {logging_mixin.py:109} INFO - [2024-04-17 03:29:08,349] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:29:08,369] {logging_mixin.py:109} INFO - [2024-04-17 03:29:08,369] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:29:08,382] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.142 seconds
[2024-04-17 03:29:38,511] {processor.py:163} INFO - Started process (PID=672) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:38,514] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:29:38,515] {logging_mixin.py:109} INFO - [2024-04-17 03:29:38,515] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:39,587] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:29:39,600] {logging_mixin.py:109} INFO - [2024-04-17 03:29:39,599] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:29:39,618] {logging_mixin.py:109} INFO - [2024-04-17 03:29:39,618] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:29:39,628] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.123 seconds
[2024-04-17 03:30:09,760] {processor.py:163} INFO - Started process (PID=721) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:30:09,762] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:30:09,763] {logging_mixin.py:109} INFO - [2024-04-17 03:30:09,762] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:30:10,930] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:30:10,936] {logging_mixin.py:109} INFO - [2024-04-17 03:30:10,934] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:30:10,955] {logging_mixin.py:109} INFO - [2024-04-17 03:30:10,955] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:30:10,967] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.212 seconds
[2024-04-17 03:30:41,104] {processor.py:163} INFO - Started process (PID=759) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:30:41,107] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:30:41,109] {logging_mixin.py:109} INFO - [2024-04-17 03:30:41,108] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:30:42,131] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:30:42,384] {logging_mixin.py:109} INFO - [2024-04-17 03:30:42,382] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:30:42,404] {logging_mixin.py:109} INFO - [2024-04-17 03:30:42,404] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:30:42,419] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.321 seconds
[2024-04-17 03:31:09,257] {processor.py:163} INFO - Started process (PID=797) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:31:09,258] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:31:09,259] {logging_mixin.py:109} INFO - [2024-04-17 03:31:09,259] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:31:10,255] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:31:10,261] {logging_mixin.py:109} INFO - [2024-04-17 03:31:10,259] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:31:10,280] {logging_mixin.py:109} INFO - [2024-04-17 03:31:10,279] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:31:10,292] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.040 seconds
[2024-04-17 03:31:40,444] {processor.py:163} INFO - Started process (PID=844) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:31:40,447] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:31:40,448] {logging_mixin.py:109} INFO - [2024-04-17 03:31:40,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:31:41,603] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:31:41,608] {logging_mixin.py:109} INFO - [2024-04-17 03:31:41,607] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:31:41,627] {logging_mixin.py:109} INFO - [2024-04-17 03:31:41,627] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:31:41,638] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.200 seconds
[2024-04-17 03:32:12,583] {processor.py:163} INFO - Started process (PID=883) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:32:12,585] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:32:12,587] {logging_mixin.py:109} INFO - [2024-04-17 03:32:12,586] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:32:13,702] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:32:13,954] {logging_mixin.py:109} INFO - [2024-04-17 03:32:13,953] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:32:13,972] {logging_mixin.py:109} INFO - [2024-04-17 03:32:13,972] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:32:13,985] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.407 seconds
[2024-04-17 03:32:44,767] {processor.py:163} INFO - Started process (PID=920) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:32:44,769] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:32:44,770] {logging_mixin.py:109} INFO - [2024-04-17 03:32:44,770] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:32:45,901] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:32:45,915] {logging_mixin.py:109} INFO - [2024-04-17 03:32:45,914] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:32:45,934] {logging_mixin.py:109} INFO - [2024-04-17 03:32:45,934] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:32:45,945] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.184 seconds
[2024-04-17 03:33:16,098] {processor.py:163} INFO - Started process (PID=968) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:33:16,101] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:33:16,102] {logging_mixin.py:109} INFO - [2024-04-17 03:33:16,102] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:33:17,216] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:33:17,221] {logging_mixin.py:109} INFO - [2024-04-17 03:33:17,219] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:33:17,239] {logging_mixin.py:109} INFO - [2024-04-17 03:33:17,239] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:33:17,250] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.158 seconds
[2024-04-17 03:33:47,389] {processor.py:163} INFO - Started process (PID=1007) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:33:47,390] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:33:47,391] {logging_mixin.py:109} INFO - [2024-04-17 03:33:47,391] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:33:48,419] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:33:48,654] {logging_mixin.py:109} INFO - [2024-04-17 03:33:48,653] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:33:48,671] {logging_mixin.py:109} INFO - [2024-04-17 03:33:48,671] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:33:48,683] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.300 seconds
[2024-04-17 03:34:19,510] {processor.py:163} INFO - Started process (PID=1054) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:34:19,512] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:34:19,513] {logging_mixin.py:109} INFO - [2024-04-17 03:34:19,513] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:34:20,521] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:34:20,534] {logging_mixin.py:109} INFO - [2024-04-17 03:34:20,533] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:34:20,556] {logging_mixin.py:109} INFO - [2024-04-17 03:34:20,556] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:34:20,567] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.062 seconds
[2024-04-17 03:35:38,226] {processor.py:163} INFO - Started process (PID=176) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:35:38,231] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:35:38,235] {logging_mixin.py:109} INFO - [2024-04-17 03:35:38,235] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:35:41,525] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:35:45,566] {logging_mixin.py:109} INFO - [2024-04-17 03:35:45,564] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:35:45,588] {logging_mixin.py:109} INFO - [2024-04-17 03:35:45,588] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:35:46,166] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py:602 DeprecationWarning: DAG.full_filepath is deprecated in favour of fileloc
[2024-04-17 03:35:46,169] {logging_mixin.py:109} INFO - [2024-04-17 03:35:46,166] {dagbag.py:602} ERROR - Failed to write serialized DAG: /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 594, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/serialized_dag.py", line 124, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 296, in _assert_active
    code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(data_ingestion_gcs_dag) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, last_updated, dag_hash) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(last_updated)s, %(dag_hash)s)]
[parameters: {'dag_id': 'data_ingestion_gcs_dag', 'fileloc': '/opt/airflow/dags/historical_data_ingestion_gcs_dag.py', 'fileloc_hash': 27268121340059120, 'data': '{"__version": 1, "dag": {"edge_info": {}, "tags": ["dtc-de"], "timetable": {"__type": "airflow.timetables.simple.OnceTimetable", "__var": {}}, "timez ... (3580 characters truncated) ... /gdelt_data.parquet"], "destination_project_dataset_table": "divij-zoomcamp-2024:gdelt2_dataset.events_stg"}], "dag_dependencies": [], "params": {}}}', 'last_updated': datetime.datetime(2024, 4, 17, 3, 35, 41, 539944, tzinfo=Timezone('UTC')), 'dag_hash': '64456d87ae5f2eb7d9b270aa184f0e16'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)
[2024-04-17 03:35:46,170] {logging_mixin.py:109} INFO - [2024-04-17 03:35:46,170] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:35:46,172] {processor.py:174} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/dag_processing/processor.py", line 168, in _run_file_processor
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/dag_processing/processor.py", line 663, in process_file
    dagbag.sync_to_db()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 608, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.6/site-packages/tenacity/__init__.py", line 382, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.6/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 622, in sync_to_db
    DAG.bulk_write_to_db(self.dags.values(), session=session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2404, in bulk_write_to_db
    orm_dags: List[DagModel] = with_row_locks(query, of=DagModel, session=session).all()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 296, in _assert_active
    code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(data_ingestion_gcs_dag) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, last_updated, dag_hash) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(last_updated)s, %(dag_hash)s)]
[parameters: {'dag_id': 'data_ingestion_gcs_dag', 'fileloc': '/opt/airflow/dags/historical_data_ingestion_gcs_dag.py', 'fileloc_hash': 27268121340059120, 'data': '{"__version": 1, "dag": {"edge_info": {}, "tags": ["dtc-de"], "timetable": {"__type": "airflow.timetables.simple.OnceTimetable", "__var": {}}, "timez ... (3580 characters truncated) ... /gdelt_data.parquet"], "destination_project_dataset_table": "divij-zoomcamp-2024:gdelt2_dataset.events_stg"}], "dag_dependencies": [], "params": {}}}', 'last_updated': datetime.datetime(2024, 4, 17, 3, 35, 41, 539944, tzinfo=Timezone('UTC')), 'dag_hash': '64456d87ae5f2eb7d9b270aa184f0e16'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)
[2024-04-17 03:36:16,278] {processor.py:163} INFO - Started process (PID=219) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:36:16,282] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:36:16,282] {logging_mixin.py:109} INFO - [2024-04-17 03:36:16,282] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:36:17,413] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:36:17,672] {logging_mixin.py:109} INFO - [2024-04-17 03:36:17,670] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:36:17,689] {logging_mixin.py:109} INFO - [2024-04-17 03:36:17,689] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:36:17,704] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.430 seconds
[2024-04-17 03:36:47,753] {processor.py:163} INFO - Started process (PID=259) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:36:47,754] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:36:47,755] {logging_mixin.py:109} INFO - [2024-04-17 03:36:47,755] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:36:48,830] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:36:48,850] {logging_mixin.py:109} INFO - [2024-04-17 03:36:48,848] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:36:48,877] {logging_mixin.py:109} INFO - [2024-04-17 03:36:48,877] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:36:48,889] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.142 seconds
[2024-04-17 03:37:19,017] {processor.py:163} INFO - Started process (PID=298) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:37:19,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:37:19,019] {logging_mixin.py:109} INFO - [2024-04-17 03:37:19,019] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:37:20,084] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:37:20,337] {logging_mixin.py:109} INFO - [2024-04-17 03:37:20,335] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:37:20,357] {logging_mixin.py:109} INFO - [2024-04-17 03:37:20,357] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:37:20,372] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.359 seconds
[2024-04-17 03:37:50,450] {processor.py:163} INFO - Started process (PID=347) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:37:50,453] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:37:50,455] {logging_mixin.py:109} INFO - [2024-04-17 03:37:50,454] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:37:51,631] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:37:51,644] {logging_mixin.py:109} INFO - [2024-04-17 03:37:51,643] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:37:51,663] {logging_mixin.py:109} INFO - [2024-04-17 03:37:51,663] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:37:51,675] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.231 seconds
[2024-04-17 03:38:21,810] {processor.py:163} INFO - Started process (PID=385) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:38:21,812] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:38:21,813] {logging_mixin.py:109} INFO - [2024-04-17 03:38:21,813] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:38:22,911] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:38:23,178] {logging_mixin.py:109} INFO - [2024-04-17 03:38:23,176] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:38:23,202] {logging_mixin.py:109} INFO - [2024-04-17 03:38:23,202] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:38:23,219] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.415 seconds
[2024-04-17 03:38:53,377] {processor.py:163} INFO - Started process (PID=429) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:38:53,379] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:38:53,379] {logging_mixin.py:109} INFO - [2024-04-17 03:38:53,379] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:38:54,474] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:38:54,487] {logging_mixin.py:109} INFO - [2024-04-17 03:38:54,486] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:38:54,506] {logging_mixin.py:109} INFO - [2024-04-17 03:38:54,506] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:38:54,516] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.145 seconds
[2024-04-17 03:39:24,663] {processor.py:163} INFO - Started process (PID=469) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:39:24,666] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:39:24,667] {logging_mixin.py:109} INFO - [2024-04-17 03:39:24,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:39:25,845] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:39:26,090] {logging_mixin.py:109} INFO - [2024-04-17 03:39:26,088] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:39:26,110] {logging_mixin.py:109} INFO - [2024-04-17 03:39:26,110] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:39:26,123] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.466 seconds
[2024-04-17 03:39:56,262] {processor.py:163} INFO - Started process (PID=507) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:39:56,264] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:39:56,265] {logging_mixin.py:109} INFO - [2024-04-17 03:39:56,265] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:39:57,414] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:39:57,430] {logging_mixin.py:109} INFO - [2024-04-17 03:39:57,428] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:39:57,456] {logging_mixin.py:109} INFO - [2024-04-17 03:39:57,456] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:39:57,470] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.212 seconds
[2024-04-17 03:40:27,605] {processor.py:163} INFO - Started process (PID=555) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:40:27,607] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:40:27,608] {logging_mixin.py:109} INFO - [2024-04-17 03:40:27,607] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:40:28,676] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:40:28,957] {logging_mixin.py:109} INFO - [2024-04-17 03:40:28,956] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:40:28,974] {logging_mixin.py:109} INFO - [2024-04-17 03:40:28,974] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:40:28,987] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.388 seconds
[2024-04-17 03:40:59,067] {processor.py:163} INFO - Started process (PID=593) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:40:59,070] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:40:59,071] {logging_mixin.py:109} INFO - [2024-04-17 03:40:59,071] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:41:00,219] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:41:00,234] {logging_mixin.py:109} INFO - [2024-04-17 03:41:00,232] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:41:00,254] {logging_mixin.py:109} INFO - [2024-04-17 03:41:00,254] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:41:00,265] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.204 seconds
[2024-04-17 03:41:30,405] {processor.py:163} INFO - Started process (PID=641) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:41:30,406] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:41:30,407] {logging_mixin.py:109} INFO - [2024-04-17 03:41:30,407] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:41:31,497] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:41:31,836] {logging_mixin.py:109} INFO - [2024-04-17 03:41:31,834] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:41:31,864] {logging_mixin.py:109} INFO - [2024-04-17 03:41:31,864] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:41:31,883] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.483 seconds
[2024-04-17 03:42:02,020] {processor.py:163} INFO - Started process (PID=679) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:42:02,021] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:42:02,022] {logging_mixin.py:109} INFO - [2024-04-17 03:42:02,022] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:42:03,129] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:42:03,148] {logging_mixin.py:109} INFO - [2024-04-17 03:42:03,146] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:42:03,175] {logging_mixin.py:109} INFO - [2024-04-17 03:42:03,175] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:42:03,189] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.175 seconds
[2024-04-17 03:42:33,322] {processor.py:163} INFO - Started process (PID=717) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:42:33,324] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:42:33,325] {logging_mixin.py:109} INFO - [2024-04-17 03:42:33,325] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:42:34,442] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:42:34,697] {logging_mixin.py:109} INFO - [2024-04-17 03:42:34,696] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:42:34,715] {logging_mixin.py:109} INFO - [2024-04-17 03:42:34,715] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:42:34,728] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.412 seconds
[2024-04-17 03:43:04,872] {processor.py:163} INFO - Started process (PID=765) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:43:04,873] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:43:04,874] {logging_mixin.py:109} INFO - [2024-04-17 03:43:04,874] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:43:06,042] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:43:06,055] {logging_mixin.py:109} INFO - [2024-04-17 03:43:06,053] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:43:06,075] {logging_mixin.py:109} INFO - [2024-04-17 03:43:06,075] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:43:06,086] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.220 seconds
[2024-04-17 03:43:36,220] {processor.py:163} INFO - Started process (PID=803) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:43:36,222] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:43:36,223] {logging_mixin.py:109} INFO - [2024-04-17 03:43:36,223] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:43:37,339] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:43:37,595] {logging_mixin.py:109} INFO - [2024-04-17 03:43:37,594] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:43:37,612] {logging_mixin.py:109} INFO - [2024-04-17 03:43:37,612] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:43:37,625] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.410 seconds
[2024-04-17 03:44:07,675] {processor.py:163} INFO - Started process (PID=852) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:44:07,678] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:44:07,679] {logging_mixin.py:109} INFO - [2024-04-17 03:44:07,679] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:44:08,919] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:44:08,934] {logging_mixin.py:109} INFO - [2024-04-17 03:44:08,932] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:44:08,954] {logging_mixin.py:109} INFO - [2024-04-17 03:44:08,954] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:44:08,964] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.295 seconds
[2024-04-17 03:44:39,105] {processor.py:163} INFO - Started process (PID=890) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:44:39,109] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:44:39,110] {logging_mixin.py:109} INFO - [2024-04-17 03:44:39,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:44:40,154] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:44:40,404] {logging_mixin.py:109} INFO - [2024-04-17 03:44:40,402] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:44:40,422] {logging_mixin.py:109} INFO - [2024-04-17 03:44:40,421] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:44:40,435] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.334 seconds
[2024-04-17 03:45:10,533] {processor.py:163} INFO - Started process (PID=942) to work on /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:45:10,537] {processor.py:642} INFO - Processing file /opt/airflow/dags/historical_data_ingestion_gcs_dag.py for tasks to queue
[2024-04-17 03:45:10,538] {logging_mixin.py:109} INFO - [2024-04-17 03:45:10,538] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:45:11,710] {processor.py:654} INFO - DAG(s) dict_keys(['data_ingestion_gcs_dag']) retrieved from /opt/airflow/dags/historical_data_ingestion_gcs_dag.py
[2024-04-17 03:45:12,082] {logging_mixin.py:109} INFO - [2024-04-17 03:45:12,080] {dag.py:2396} INFO - Sync 1 DAGs
[2024-04-17 03:45:12,098] {logging_mixin.py:109} INFO - [2024-04-17 03:45:12,096] {dag.py:2415} INFO - Creating ORM DAG for data_ingestion_gcs_dag
[2024-04-17 03:45:12,111] {logging_mixin.py:109} INFO - [2024-04-17 03:45:12,111] {dag.py:2935} INFO - Setting next_dagrun for data_ingestion_gcs_dag to 2024-04-16T00:00:00+00:00
[2024-04-17 03:45:12,131] {processor.py:171} INFO - Processing /opt/airflow/dags/historical_data_ingestion_gcs_dag.py took 1.603 seconds
